### ISSUE TITLE
Select element for use with StartAudioContext

### ISSUE THREAD

**Issue by tatecarson** [nexus-js/ui#103]
I'm trying to use a toggle on mobile and use the toggle as the element that the user has to touch to get the context to turn on. I think I have some confusion about how everything is working. My toggle is inside of a div named synth but `  StartAudioContext(Tone.context, document.getElementById("synth"));
` does not seem to be working. When inspecting it I can't ever touch that div, just the SVG below it. What's the best way to select the UI element to use it to start the audio context?

**Comment by taylorbf** [comment]
Hey Tate, I use non-nexusui elements to start mobile. 

The normal NexusUI .on('change'... callback is not sufficient, as you've figured out, because it is not directly tied to a mouse event (even if it appears to be).

Attaching additional mouse event handlers to NexusUI divs will likely be inconsistent or not work at all because a NexusUI element blocks the event proliferation in order to stop default browser events from happening (like text select , drag, and others).

There is an example in example/demo.html of using Tone's method on a regular text div. For mobile projects I often do a full screen text overlay with "Start" text or something.

There might be a way to make it work with a NexusUI toggle that I haven't thought of... Definitely share if you think of one!
