### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by mscottnelson** [nexus-js/ui#106]
I'd like to help fix some of the documentation issues (eg undocumented features). Ironically, I can't find any documentation or reference on how to generate the documentation. It looks like JSDoc? What is the generator / process for generating documentation from JSDoc annotations?

**Comment by taylorbf** [comment]
Sure. We're using documentation.js for documentation. This is the setup as I remember it -- 

First install documentation.js globally

`npm install -g documentation`

(may need to sudo that)

Then in the NexusUI repository folder, you can run this to compile the docs:

`documentation build lib/** -f json -o api/api.json -w`

This scans through all files in ./lib/ and compiles the inline jsdoc-style documentation comments and puts them in ./api/api.json. I API website ./api/index.html uses moustache.js to turn that JSON data into the HTML of the page.

You should see the changes in your local version of nexus-js/ui/index.html . To see them live online, you need to go to the gh-pages branch of this repository and update it from master branch.

*However*, this is a bit of a custom documentation rig... because I wanted to mix in tutorials with the normal API. So, some parts of the documentation are tutorials (for example, [the part about tuning](https://nexus-js.github.io/ui/api/#tune)). That is all hand-written HTML in the ./api/index.html file, I think. I know it is a bit ugly, but I *really* wanted to include tutorials as part of the documentation. It was one of the main things that I felt was missing in the previous version of this toolkit.

What features are you thinking of documenting?

There are also some standing pull requests that I have been delinquent about ...Feel free to look at those as well. Have not been able to maintain this well of late, although thankfully it is at a pretty stable state right now.

**Comment by mscottnelson** [comment]
I'd like to start by setting up these documentation dependencies in devDependencies, adding an npm script for doc gen, and briefly explaining guidelines for contributing in CONTRIBUTING.md. Regarding missing documentation, I was going to attempt to close another issue, https://github.com/nexus-js/ui/issues/105, relating to a misunderstanding of how the Sequencer is configured...the documentation did not discuss the Sequencer 'mode' referring to button 'mode' rather than sequence 'mode'. That might also involve additional clarification about adjusting the stepper of the Sequencer rather than the mode to achieve changes in walking the sequence.

Regarding PRs, I'd be happy to review as I have time. If it would be convenient for you to also give me admin access, I'd be happy to also help manage merges resulting from successful PRs.

**Comment by taylorbf** [comment]
Sounds fabulous. Happy to have you on board. After the items you mentioned (which are all needed), feel free to fix any errors you see in the docs as well.
