### ISSUE TITLE
Select not returning value

### ISSUE THREAD

**Issue by CVaughanUK** [nexus-js/ui#114]
I'm sure I must be doing something wrong. For some reason I cannot get the select object to return the string value of the option selected, and store it as a variable. 

` osc1Select.on('*', function(val) {
     osc1Wave = val;
 });`

and then later

`if(osc1Wave === 'sine') {
        osc1Out = osc1.sinewave(freq) * osc1Level;
    }`

Yet no sound is produced and the wave isn't selected, am I missing something here?

**Comment by taylorbf** [comment]
The current version (2) uses specific event listeners. I think you want .on('change', ... rather than .on('*', ...

**Comment by CVaughanUK** [comment]
Have tried with change originally and that didn't seem to return anything either!

**Comment by taylorbf** [comment]
I think the issue is that the data that the interface gives you is not the text ('sine') but is an object containing the text and the selected index.

You can use `console.log(val)` to see that object, or check out this codepen which logs the result when you interact with the Select interface:

[https://codepen.io/taylorbf/pen/RxGOgy?editors=1011](https://codepen.io/taylorbf/pen/RxGOgy?editors=1011)

Let me know if this works for you!

**Comment by CVaughanUK** [comment]
Thank you that's solved it!
