### ISSUE TITLE
Vertical slider offset error

### ISSUE THREAD

**Issue by AntoineMaiorca** [nexus-js/ui#119]
Hello,
I was trying to create a vertical slider by having the height be bigger than the width.
The slider draws correctly but there seems to be some problem with an offset relative to the position where the slider is clicked. At some point in the slider movement , there is an inversion of values (dragging up actually brings the slider down).

var slider = new Nexus.Slider('#slider',{
  mode: 'absolute'
});
slider.resize(50,150);

**Comment by taylorbf** [comment]
This does look like a bug -- when a horizontal slider is resized and becomes a vertical slider, the mouse interactions are still treating it like a horizontal slider.

For now, you can create a vertical slider by giving the slider an initial `size` parameter, rather than using `resize`:

```
var slider = new Nexus.Slider('#slider',{
  size: [50,150],
  mode: 'relative'
});
```

But I will check this out to see why its orientation is not updating on resize ... The code for it appears to be in place.

**Comment by CarloCattano** [comment]
Still this is an issue . I love this library but now I really need some solution since it makes the slider unusable , also with the provided solution .
Would love to hear an update on this one

**Comment by taylorbf** [comment]
Understood, I will look to fix this asap, hopefully in the next week or so. Thanks for bringing this to my attention!

**Comment by tatecarson** [comment]
This issue should be fixed now. Let me know if you have any other problems.
