### ISSUE TITLE
Slider scaling

### ISSUE THREAD

**Issue by nebrekab** [nexus-js/ui#125]
Hi,

When the slider is scaled the drag handle does not move correctly with the mouse

Example: https://codepen.io/nebrekab/pen/wEXBbZ

Is there a way for scaling to be taken into account?

I see the [older version of NexusUi](http://nexusosc.com/api/) had `nx.setViewport( scale )` 

Is there an equivalent that could help?

Thank you

**Comment by taylorbf** [comment]
Hi Ben,

Yes there is a solution. So for clarity this is not about resizing a slider using `size`, but instead using CSS `zoom` to scale the viewport. In your demo you zoomed the page to 0.5 to make the page appear smaller. And the mouse motion on the slider does not line up in that case.

You can add this line to the end of your JS in your codepen to solve the issue:

`slider.position.sensitivity = 2`

To explain, `slider.position` is a class that manages the linear motion of the slider. It has a property for sensitivity. Setting `sensitivity` to 2 means that every 1 pixel of mouse motion will render as 2 pixels of linear movement on the slider. Since you are zoomed to 0.5, this reduces it back to 1px.

Sorry that there are some depths of these minor classes that were not documented!

**Comment by nebrekab** [comment]
@taylorbf excellent - thanks!

I've updated the CodePen with the sensitivity update.
