### ISSUE TITLE
Select Widget is Unselectable

### ISSUE THREAD

**Issue by luisArandas** [nexus-js/ui#141]
The select button doesn't dropdown on click. 
Using the default code that is in the api, just a simple:

var select = new Nexus.Select('#target', {
  'size': [100, 30],
  'options': ['default', 'options']
});
select.on('change', function(v) {
  console.log(v);
});
Plus div id="target" class="target"/div
It is not selectable, anyone got this bug?

**Comment by taylorbf** [comment]
I put the code you posted into a codepen and it works fine here. Is this an issue with a specific platform / browser?

https://codepen.io/taylorbf/pen/BMyeLd?editors=1111

**Comment by luisArandas** [comment]
<img width="423" alt="screen shot 2019-01-23 at 14 34 47" src="https://user-images.githubusercontent.com/30077568/51613764-1bf38400-1f1c-11e9-9a16-2dd502b226a8.png">
Now it's even worse lol, Just a full rectangle
The code is exactly the same!!
I even tested with span instead of div

**Comment by luisArandas** [comment]
This is a biiig code, so I think it might be something interfering.
I have it hosted here on github but you can see it at www.akson.xyz and press space!
Please tell me if you can see it
Best, Luis

**Comment by luisArandas** [comment]
The thing is that I need a lot of these guys and yours from Nexus seem nice and easy to get into :/
Gonna try again today
Best, Luis

**Comment by taylorbf** [comment]
Hi Luis, it might be that there's a typo where you create the div for the select object -- you have `<div id="select" class"select"></div>` and it should be `class="select`. Does that clear up this issue? 

I'm afraid I can't help debug much more than that. Since Nexus.Select does work in an isolated context, it seems like this issue is caused by some other aspect of your project -- either that typo, or possibly one of the window event listeners that you have which throw errors sometimes, or something else. You may need to strip back this project and add items piece by piece to figure out what is causing the issue here. Best of luck!

**Comment by taylorbf** [comment]
A few more suggestions to get you through this --

Your select div has a style of `overflow:hidden` which might hide the dropdown menu

The select object itself has a style of `-webkit-appearance: none` from somewhere in your styles, which is what is causing it to be a plain rectangle instead of looking like a select object

Lastly, it looks like the select's dropdown actually is working when the select object is clicked, but it is not visible for some reason. I notice this because a scrollbar appears and disappears when I click on the select object -- i.e. the page body is getting taller because the dropdown is opening. But the dropdown is not visible to us -- maybe it is a z-index issue? Maybe the Three.js overlay is causing some sort of interference.

Again, best of luck figuring this out!

**Comment by luisArandas** [comment]
Thank you very much for the help.
I am testing what you say, that bar doesn't seem to appear to me.
Well, all the buttons and so on happen to have no problem with Three.js, I am testing now the z-index and it is quite the same.
The -webkit-appearance: none I've seen it, unchecked in the developer console works. But I have nothing telling that in the css. I don't understand.
Thank you anyway!
Best, Luis

**Comment by taylorbf** [comment]
Sure, sorry I can't be of more help. I did try removing all the HTML and adding a simple HTML select object, and it acts the same way (options do not appear on click). Maybe another JS library like bootstrap is getting in the way somehow -- you might try removing those libs one by one and testing, as well as removing any mousedown event listeners that might be intercepting a mouse click.

**Comment by luisArandas** [comment]
Yes sure!
Best, Luis
