### ISSUE TITLE
Missing Visualization pages in API docs

### ISSUE THREAD

**Issue by pierredewilde** [nexus-js/ui#148]
When selecting any Visualization pages, nothing is displayed.

https://nexus-js.github.io/ui/api/#Meter
https://nexus-js.github.io/ui/api/#Oscilloscope
https://nexus-js.github.io/ui/api/#Spectrogram

The console logs an error:
```
moustache.min.js:1 Uncaught TypeError: Cannot read property 'name' of undefined
    at Context.lookup (moustache.min.js:1)
    at Writer.escapedValue (moustache.min.js:1)
    at Writer.renderTokens (moustache.min.js:1)
    at Writer.render (moustache.min.js:1)
    at Object.render (moustache.min.js:1)
    at doc ((index):1791)
    at load ((index):1910)
    at (index):1774
```

**Comment by juanalonso** [comment]
please, is it possible to have a look at that? Thank you very much.

**Comment by vladansaracpv** [comment]
I think it is related to api.json file. I'm not sure wether it is done on purpose, or by mistake, but Meter / Oscilloscope / Spectagram don't have their names set as value for "name" key, Instead, there are multiple objects with values like "context" / "connect" / "disconnect" used for naming. But in reality those are the names of their methods.

Here I'm showing just the Button related json. (see name: "Button"). This value is used to match the url hash with the given object.

![Button](https://user-images.githubusercontent.com/7712699/65650540-a6403a80-e00b-11e9-9bf4-e9eef54d6015.PNG)

After the api.json is being parsed and all the objects have been created (named after key => "name"), it looks like this:

![nexus1](https://user-images.githubusercontent.com/7712699/65650486-6aa57080-e00b-11e9-8311-e338a1a9071e.PNG)

We don't see objects for Meter/Oscilloscope/Spectagram, as in api.json they were represented by their methods, which in this case are connect / disconnect / context. To be worse, if two objects share the same method names as Oscilloscope and Spectagram do, the later will overwrite the Oscilloscope, which is why we see the following:

![connect](https://user-images.githubusercontent.com/7712699/65650812-97a65300-e00c-11e9-94d8-8b9bb70bab10.PNG)

I managed to fix it by making this three json parts to be like all the others, but I'm not sure author had that in mind (maybe it is related to the fact that they must get Nexus audio context from the outside and connect to it, or maybe the script that's generating this api.json file just started to screw around

**Comment by vladansaracpv** [comment]
I figure it was all because of this line in all 3 files:

`import { context } from "../main";`

Think it made a problem to the script that is generating api.json file, as it thought that brackets represent class (with comments above it).

This is the state before:

![context](https://user-images.githubusercontent.com/7712699/65651860-0638e000-e010-11e9-9b84-6b845b3ba156.PNG)

And this is after I moved it above the comments:

![context2](https://user-images.githubusercontent.com/7712699/65651933-4304d700-e010-11e9-9849-1cf9be38584e.PNG)

Finally they are again here :))

![spectogram](https://user-images.githubusercontent.com/7712699/65651991-7f383780-e010-11e9-9025-945947ee7a18.PNG)

![oscilloscope](https://user-images.githubusercontent.com/7712699/65651993-83645500-e010-11e9-8f18-d61271ecc659.PNG)

![meter](https://user-images.githubusercontent.com/7712699/65651997-85c6af00-e010-11e9-93a8-3fdf2b3de970.PNG)

**Comment by styk-tv** [comment]
Hi @vladansaracpv Is there any chance you could push this back as a PR but based on a clean branch created out of fresh master fork?

**Comment by vladansaracpv** [comment]
Hey @styk-tv,
I've created Pull Request [159](https://github.com/nexus-js/ui/pull/159)

**Comment by tatecarson** [comment]
Thanks for the PR @vladansaracpv. The docs are now updated.
