### ISSUE TITLE
Is there a roadmap for this project with future features or enhancements?

### ISSUE THREAD

**Issue by rohitkrishna094** [nexus-js/ui#166]
I am planning on using this library(along with something like tone js) to build a fl studio like app on react(not sure how feasible it is). But I also wanted to contribute to this project if I could. 

So I was wondering, are there any future plans for this project(some trello or jira board of sorts)? Like extra features that are in pipeline etc? If so, I would love to contribute heavily to this repo. 

I read the previous issue #73 and I understand that a lot has changed. But if there is anything else that could be improved in 2020 and if we could add more features to make this insanely robust, it would be cool.

Also I was thinking that it would be amazing to have a discord channel or similar and encourage other people to contribute to this project as well. 

What do you guys think?

**Comment by tatecarson** [comment]
Hello, so @taylorbf is no longer actively working on the project. He handed it off to me and I'm slowly learning the code base and figuring out future directions. I am currently in the Phd program Ben was in, so free time is a little bit of an issue. 

There is no future plans list but I am not opposed to starting one. I share Ben's vision for keeping the library geared towards web audio applications,  as there are many other UI libraries that work well with other programs like Max and SuperCollider. 

One major thing I have through about but haven't had time to do yet is exploring web components. My thoughts were that this would allow nexus ui elements to be used much more easily in react/vue applications and at the same time make it even easier for novice programmers to use in their apps by just using html tags and changing properties. 

I am unfamiliar with discord, I know what it is but have never used it. I will look into that. 

I really welcome contributions and ideas so if you want to go ahead and setup a discord or offer ideas of feature improvements i'm all ears.

**Comment by rohitkrishna094** [comment]
Yes it would be cool if we had react or angular or vue version of this library. I have never heard of web components, but they sound good. It seems like you don't need to rewrite the library for major frameworks over and over again(like react, angular or vue). 

And discord was just an example. We could use slack or gitter as well. I have used only discord(since its completely free afaik while slack has some limits in free version). Also I have joined few discord channels where there are tons of beginners and I am pretty sure they would be willing to work on this library(if marketed). 

I don't have any features in mind right now(I am not that good at music and have only used FL Studio few times so don't know much about electronic music either). But one thing that we could do is to migrate the codebase to newer syntax thereby reducing the number of lines. The code base right now has about 8k lines. 

I am pretty sure we could also add some more config options for some components(like from my other issue where I wanted to change padding between cells in a sequencer). Not to mention, we could add more web ui components for music(might have to research a bit and see how other vst plugins like from native instruments are designed).

One last thing is, even if we don't have a roadmap, it could be nice to have a feature list that we want to implement in future(we could use github projects, the tab at the top)

**Comment by brucelane** [comment]
I use https://github.com/rakannimer/react-nexusui and I like it!

**Comment by rohitkrishna094** [comment]
Oh so a react port is already there? 😢 I thought I could do it.

**Comment by brucelane** [comment]
well, we can build upon it

**Comment by tatecarson** [comment]
So I have gone ahead and created two projects to organize issues and plan for the future. You can find them [here](https://github.com/nexus-js/ui/projects). I can give you access to add things to the roadmap board if you would like. I am also planning on creating a more automated changelog. 

Discord seems fine so I will probably go ahead and make one. I will make an issue to remind myself to do it. 

The syntax could defiantly be worked on. I am not sure the best way to go about updating that without breaking things. I supposed I can make a new branch that we can all contribute to then merge when that is all working. What sort of code enhancements where you thinking of? 

There can probably be new config options, but we don't want to make the components overly complicated. I'm hoping that some of these issues with customization can be solved by moving to web components. 

Also, just so you know, there used to be [many more components](http://nexusosc.com/api/#nexusui-api-nx). Ben paired them down to what you see here because of the work it took to just maintain these. So I would love to include more components but they are limited by my time and by the amount of community input. I have thought about creating a separate set of experimental components and offering them up with less support if people want to use them. I may do that in the future.

**Comment by vladansaracpv** [comment]
Hey @tatecarson, glad you're continuing the work. I've been converting the project to typescript so that I can learn more about it and for the sake of fun :) I'm available & eager to contribute to the project as it gave me so much joy so far.

**Comment by rohitkrishna094** [comment]
@tatecarson Hey that sounds great. I will join discord once you set it up. For code changes, I was just thinking to update the codebase to use modern javascript features(of course without breaking any of the current functionality for any of the current consumers or clients). 

Anyway I am just going through the codebase right now. 

That said, I am closing the issue, since I think it has been resolved since you added roadmap and an issue for community channel(discord) setup as well. 

Again, thanks a lot for your time.
