### ISSUE TITLE
Multitouch piano support

### ISSUE THREAD

**Issue by wiped1** [nexus-js/ui#176]
Currently, the piano interface does not support multitouch presses. 
Buttons start to glitch-out and emit on/off events randomly when 3 or more keys are pressed (tested on safari ipad ios13.3). Sometimes the key visual get stuck in pressed state, even though touch was released.

Other components suffer similar issue, though multitouch support is not that crucial like in a piano.

**Comment by pendragon-andyh** [comment]
I have created a [pull-request](https://github.com/nexus-js/ui/pull/189/commits/cafc9f2ea325d8ec4604278bb28c19927c1566e1) for this. [Demo](https://pendragon-andyh.github.io/junox/demo/juno60-nexusUI.html) from one of my repos.

**Comment by rowild** [comment]
Wow, that's mega cool!

**Comment by tatecarson** [comment]
On my Ipad (12.4.7) with Safari or Firefox, the keyboard does not show when running your demo up so I can not test this. Any ideas why?

**Comment by pendragon-andyh** [comment]
I am not sure if Apple's browser supports the AudioWorklet that I am using
to implement the synth.

I'll have a play tonight and see if I can work out what's up.

**Comment by pendragon-andyh** [comment]
Hi @tatecarson 

### For this PR

For the current code on the http://nexus-js.github.io/ui/api/#Piano page, hold down a note on the left side of the keyboard, then press a note on the right side. Slowly start dragging your fingers towards the centre of the keyboard. Only one note is ever highlighted at a time.

Then run my PR locally and try the same test.

Note: The changes to the multislider.js file were because `jshint` was complaining about ternary statements being split over multiple lines.

### For my JunoX demo

I have confirmed that the AudioWorklet does not work on IOS devices (see https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet#Browser_compatibility). I had a quick try with the "audioworklet-polyfill", but that entirely misses the use-case of sub-classing the AudioWorkletNode. At some point I will experiment with correcting the polyfill.

**Comment by tatecarson** [comment]
Everything looks good, thanks for the PR.
