### ISSUE TITLE
multitouch keyboard

### ISSUE THREAD

**Issue by jeffcrouse** [nexus-js/ui#32]
When I use a keyboard widget on my Android phone, it works great as long as there is only one touch. But when I add more than 1, it immediately stops sending anything but "on: 0".  Is there as setting I am missing perhaps?

**Comment by Larsberg** [comment]
I'm running into the same issue here

**Comment by jefftimesten** [comment]
Not a great fix, but I've found that commenting out the entire body of keyboard.prototype.click makes it usable, since keyboard.prototype.move works perfectly well, and the "click" and "move" functions always get called together.
Perhaps this will help someone with more understanding of Nexus piece together what might be up.

**Comment by taylorbf** [comment]
Interesting, thank you for sharing that fix @jefftimesten. This is an issue I would like to fix and will do so (I'll also accept PRs that fix it if you find a way). I'm sorry it may take me a week to look at it due to helping with [NIME](http://nime2015.lsu.edu) this week, but I will do so. Sorry for the delay -- glad you are using Nexus!

Ben

**Comment by jefftimesten** [comment]
FWIW: I literally just pasted the keyboard.prototype.move into keyboard.prototype.click and it works fine for us.

**Comment by taylorbf** [comment]
Hey Jeff,

So, the solution you mentioned isn't satisfactory for general use because it breaks the interaction on iOS.

The real problem here is that I no longer have an Android to test on. 

I've edited the keyboard widget so that the move and click functions are more similar. You can try the latest version in the dev branch if you'd like, to test.

If this update doesn't work, we'll have to rely on your copy-paste hack until I can get hold of a device to work with.

**Comment by cesar3dartist** [comment]
THe keyboard code has multitouch set off by default. Look it up in nexusUI.js:

this.multitouch = false; // will auto switch to true if experiences 2 simultaneous touches

**Comment by mscottnelson** [comment]
Closing as refers to v1 of nexus/ui. Will reopen / investigate if still an issue.
