### ISSUE TITLE
rack problem: Cannot set property 'boxSizing' of undefined

### ISSUE THREAD

**Issue by gilfuser** [nexus-js/ui#86]
Hi.
First I would like to thank all involved in this great project. I can foresee great things made with it.

I just started to try it. My idea is to use nexus-js to communicate via osc with supercollider, using it together with Node, Sockets.io and node-js to make a collaborative gui on the web.

Exploring the session "Creating a Rack" in the API, I couldn't reproduce the example. I'm getting the following error in the browser inspector:
```
Uncaught TypeError: Cannot set property 'boxSizing' of undefined
    at Rack.buildInterface (rack.js:63)
    at new Rack (rack.js:58)
    at gui.js:1
buildInterface @ rack.js:63
Rack @ rack.js:58
(anonymous) @ gui.js:1
```
Here is my code:

the server.js code:
```
var express = require('express');
var app = express();
app.use(express.static('public'));
var server = require('http').Server(app);
var server = app.listen(5000);
app.use('/scripts', express.static(__dirname + '/node_modules/nexusui/dist/'));
```
the HTML:
```
<html>
<head>
  <script src="/scripts/NexusUI.js"></script>
  <script src="gui.js"></script>
</head>
<body>
  <div id="synth"> 
    <span nexus-ui="dial" id="freq"></span>
    <span nexus-ui="dial" id="volume"></span>
    <span nexus-ui="dial" id="mod"></span>
  </div>
</body>
</html>
```

and the JS:
```
var synth = new Nexus.Rack('#synth');

synth.freq.value = 0.25;
synth.volume.value = 0.5;
synth.mod.value = 0.75;

synth.freq.on('change',function(v) {
  console.log(v);
});
```
Maybe I'm just missing something basic.

best regards,
Gil

**Comment by taylorbf** [comment]
Hey there Gil,

Nice example. Yes this will work fine, but you need to load your gui.js after the body of the document has been created. Right now, in your gui.js code, `new Nexus.Rack('#synth')`  looks for the "#synth" div and doesn't find it, because it hasn't been created yet.

You can either wrap your gui.js code in some kind of document onload function (probably the preferred method), or you can load your gui.js at the end of your HTML file:

```html
<html>
<head>
  <script src="/scripts/NexusUI.js"></script>
</head>
<body>
  <div id="synth"> 
    <span nexus-ui="dial" id="freq"></span>
    <span nexus-ui="dial" id="volume"></span>
    <span nexus-ui="dial" id="mod"></span>
  </div>
</body>
<script src="gui.js"></script>
</html>
```

Best of luck with your collaborative GUI -- sounds great!!
