### ISSUE TITLE
How to use oscilloscope with web api

### ISSUE THREAD

**Issue by gkvoelkl** [nexus-js/ui#98]
Hi 

I tried to use oscilloscope with web api

```
var gain = context.createGain();
gain.connect(context.destination);

var oscilloscope = new Nexus.Oscilloscope('oscilloscope');
Nexus.context = context;
oscilloscope.connect(gain);

```
I get an error

SyntaxError (DOM Exception 12): The string did not match the expected pattern.

Any working example?

**Comment by taylorbf** [comment]
The line `Nexus.context = context` should be placed before you create the oscilloscope. In fact I would place it just once at the very top of your NexusUI code. I'm not sure if that is what's causing this particular problem.

Another guess - try `new Nexus.Oscilloscope('#oscilloscope');` instead of `new Nexus.Oscilloscope('oscilloscope');`  ... I don't think that should be causing this but please let me know if it is. I assume you have a div in your HTML that has an ID of 'oscilloscope'?

A working demo of a spectrogram (same API) is up [here](https://nexus-js.github.io/ui/example/demo.html). It is using the Nexus.Rack() method of creating interfaces, though, so a little bit different.

**Comment by gkvoelkl** [comment]
That's the solution.
